# Embed one committed binary asset into a target as a generated byte-span
# function. PNG decode stays a runtime/application concern; this helper only
# removes runtime path discovery from installed games.

include_guard(GLOBAL)

function(glyphcade_embed_asset TARGET NAME FILE)
  if (NOT TARGET ${TARGET})
    message(FATAL_ERROR "glyphcade_embed_asset: target '${TARGET}' does not exist")
  endif ()
  if (NOT EXISTS "${FILE}")
    message(FATAL_ERROR "glyphcade_embed_asset: file '${FILE}' does not exist")
  endif ()

  string(MAKE_C_IDENTIFIER "${NAME}" _identifier)
  if (NOT _identifier STREQUAL NAME)
    message(FATAL_ERROR
      "glyphcade_embed_asset: NAME '${NAME}' is not already a C++ identifier "
      "(use '${_identifier}')")
  endif ()

  set(_root "${PROJECT_BINARY_DIR}/generated/assets/${TARGET}")
  set(_include_root "${_root}/include")
  set(_header "${_include_root}/glyphcade/generated_assets/${NAME}.hpp")
  set(_source "${_root}/${NAME}.cpp")

  add_custom_command(
    OUTPUT "${_header}" "${_source}"
    COMMAND ${CMAKE_COMMAND}
            -DINPUT=${FILE}
            -DHEADER=${_header}
            -DSOURCE=${_source}
            -DNAME=${NAME}
            -P ${PROJECT_SOURCE_DIR}/cmake/embed_asset.cmake
    DEPENDS "${FILE}" ${PROJECT_SOURCE_DIR}/cmake/embed_asset.cmake
    COMMENT "Embedding asset ${FILE} as ${NAME}()"
    VERBATIM
  )

  target_sources(${TARGET} PRIVATE "${_source}" "${_header}")
  target_include_directories(${TARGET} PRIVATE "${_include_root}")
endfunction()
