# Assert that committed PNGs and their authoring records cannot drift apart.

cmake_minimum_required(VERSION 3.28)

if (NOT DEFINED ASSET_DIR)
  message(FATAL_ERROR "check_assets.cmake needs -DASSET_DIR=")
endif ()
if (NOT DEFINED MANIFEST)
  set(MANIFEST "${ASSET_DIR}/manifest.json")
endif ()
if (NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "asset manifest does not exist: ${MANIFEST}")
endif ()

file(READ "${MANIFEST}" _json)
string(JSON _schema GET "${_json}" schema_version)
if (NOT _schema EQUAL 1)
  message(FATAL_ERROR "unsupported asset manifest schema: ${_schema}")
endif ()

string(JSON _count LENGTH "${_json}" assets)
if (_count EQUAL 0)
  message(FATAL_ERROR "asset manifest lists no assets")
endif ()

set(_listed "")
set(_names "")
math(EXPR _last "${_count} - 1")
foreach (_i RANGE 0 ${_last})
  string(JSON _name GET "${_json}" assets ${_i} name)
  string(JSON _file GET "${_json}" assets ${_i} file)
  string(JSON _kind GET "${_json}" assets ${_i} kind)
  string(JSON _generator GET "${_json}" assets ${_i} generator)
  string(JSON _generated_at GET "${_json}" assets ${_i} generated_at)
  string(JSON _width GET "${_json}" assets ${_i} width)
  string(JSON _height GET "${_json}" assets ${_i} height)
  string(JSON _bytes GET "${_json}" assets ${_i} bytes)
  string(JSON _sha GET "${_json}" assets ${_i} sha256)
  string(JSON _prompt GET "${_json}" assets ${_i} generation_prompt)

  if (_name STREQUAL "" OR _file STREQUAL "" OR _kind STREQUAL "" OR
      _generator STREQUAL "" OR _generated_at STREQUAL "" OR
      _prompt STREQUAL "")
    message(FATAL_ERROR "asset ${_i} has an empty identity or provenance field")
  endif ()
  if (_width LESS_EQUAL 0 OR _height LESS_EQUAL 0 OR _bytes LESS_EQUAL 0)
    message(FATAL_ERROR "asset ${_name} has invalid dimensions or byte count")
  endif ()
  string(LENGTH "${_sha}" _sha_length)
  if (NOT _sha_length EQUAL 64 OR _sha MATCHES "[^0-9a-f]")
    message(FATAL_ERROR "asset ${_name} has an invalid SHA-256: ${_sha}")
  endif ()
  cmake_path(IS_ABSOLUTE _file _file_absolute)
  if (_file_absolute OR _file MATCHES "(^|/)\\.\\.(/|$)")
    message(FATAL_ERROR "asset path must stay below assets/: ${_file}")
  endif ()

  if (_name IN_LIST _names)
    message(FATAL_ERROR "duplicate asset name in manifest: ${_name}")
  endif ()
  if (_file IN_LIST _listed)
    message(FATAL_ERROR "duplicate asset path in manifest: ${_file}")
  endif ()
  list(APPEND _names "${_name}")
  list(APPEND _listed "${_file}")

  set(_path "${ASSET_DIR}/${_file}")
  if (NOT EXISTS "${_path}")
    message(FATAL_ERROR "manifest asset is missing: ${_file}")
  endif ()
  file(SIZE "${_path}" _actual_bytes)
  if (NOT _actual_bytes EQUAL _bytes)
    message(FATAL_ERROR
      "asset byte count mismatch for ${_file}: manifest=${_bytes} actual=${_actual_bytes}")
  endif ()
  file(SHA256 "${_path}" _actual)
  if (NOT _actual STREQUAL _sha)
    message(FATAL_ERROR
      "asset hash mismatch for ${_file}:\n  manifest: ${_sha}\n  actual:   ${_actual}")
  endif ()
endforeach ()

file(GLOB_RECURSE _pngs RELATIVE "${ASSET_DIR}" "${ASSET_DIR}/*.png")
list(SORT _pngs)
list(SORT _listed)
if (NOT _pngs STREQUAL _listed)
  message(FATAL_ERROR
    "manifest coverage differs from committed PNGs:\n  manifest: ${_listed}\n  files:    ${_pngs}")
endif ()

message(STATUS "asset-manifest: CLEAN (${_count} asset(s))")
